### ISSUE TITLE
Permissions don't work

### ISSUE THREAD

**Issue by TheOnlyRealTGS** [ProjectInfinity/BookManager-Reloaded#2]
Using PEX

**Comment by ProjectInfinity** [comment]
Permissions work, PEX doesn't. Use a Permission manager that works.

**Comment by TheOnlyRealTGS** [comment]
This is the first plugin I've used in a very long time which PEX doesn't work with. What's wrong with PEX? 
(Please read this: https://docs.google.com/document/d/1BIgAU7senSG1hY0BjQAQFAnbuOqFhpln7ffN6pkOp4s/edit)

**Comment by ProjectInfinity** [comment]
The problem is with PEX and cannot lie with any of my code because all permissions related code is **DIRECTLY** using the Bukkit API and as such cannot and is not modified beyond checking if Player.hasPermission() returns true.

You'll notice time and time again that PEX has unexplainable problems with completely vanilla permission checks. It doesn't get more basic than Player.hasPermission().

**Comment by TheOnlyRealTGS** [comment]
Now I'm no developer, so I won't begin to argue about things I don't know anything about, but PermissionsEX is the most advanced permission plugin out there, which are used by the best server owners, and I highly doubt there isn't a easy way to make your brilliant plugin compatible with it. The plugin was last updated 1 year ago, and much of pex's plugins have been solved in the meantime, and I could imagine your code is a bit outdated too.

**Comment by ProjectInfinity** [comment]
.hasPermission() has not changed in a long long long long time. The issue lies with PEX and was the reason I decided to stop using it myself, all good servers stopped using it as PEX is now the worst permission manager available.

**Comment by TheOnlyRealTGS** [comment]
Alright, we ain't going any further with this discussion, but just consider that a few hundred thousand people use pex so it would be great if you could add support for them :)
